# Generated by Django 5.1.5 on 2025-01-15 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
