# Generated by Django 5.1.5 on 2025-01-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_transaction_category_remove_transaction_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
