# Generated by Django 5.2 on 2025-04-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintxnapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Set to True if this is a recurring transaction'),
        ),
    ]
